#!/bin/bash
# Video + Audio merge script
# Generated by Training Video Generator

set -e

# Configuration
TOPIC="{{TOPIC}}"
VIDEO_INPUT="recordings/${TOPIC}.mov"
AUDIO_INPUT="audio/${TOPIC}/narration.mp3"
OUTPUT="output/${TOPIC}-final.mp4"

# FFmpeg settings
VIDEO_CODEC="libx264"
VIDEO_CRF="22"
VIDEO_PRESET="slow"
AUDIO_CODEC="aac"
AUDIO_BITRATE="192k"

# Ensure output directory exists
mkdir -p "output"

echo "🎬 Merging Video and Audio"
echo "Topic: $TOPIC"
echo "Video: $VIDEO_INPUT"
echo "Audio: $AUDIO_INPUT"
echo "Output: $OUTPUT"
echo ""

# Verify input files exist
if [ ! -f "$VIDEO_INPUT" ]; then
    echo "❌ Error: Video file not found: $VIDEO_INPUT"
    exit 1
fi

if [ ! -f "$AUDIO_INPUT" ]; then
    echo "❌ Error: Audio file not found: $AUDIO_INPUT"
    exit 1
fi

echo "⏳ Processing with FFmpeg..."

# Merge video and audio
ffmpeg -i "$VIDEO_INPUT" -i "$AUDIO_INPUT" \
       -c:v "$VIDEO_CODEC" -preset "$VIDEO_PRESET" -crf "$VIDEO_CRF" \
       -c:a "$AUDIO_CODEC" -b:a "$AUDIO_BITRATE" \
       -movflags +faststart \
       "$OUTPUT" -y

echo ""
echo "✅ Merge complete!"
echo ""

# Show video information
echo "📊 Video Information:"
ffprobe -v quiet -print_format json -show_format -show_streams "$OUTPUT" | \
    jq -r '.format | "Duration: \(.duration)s | Size: \(.size / 1024 / 1024 | floor)MB"'

echo ""
echo "💾 Output: $OUTPUT"
echo "🎉 Your training video is ready!"
