#!/bin/bash
# TTS Narration generation script
# Generated by Training Video Generator

set -e

# Configuration
TOPIC="{{TOPIC}}"
BEAT_SHEET="scripts/video-scripts/${TOPIC}-beat-sheet.md"
OUTPUT_DIR="audio/${TOPIC}"
TTS_PROVIDER="{{TTS_PROVIDER}}"

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

echo "🗣️  Generating TTS Narration"
echo "Topic: $TOPIC"
echo "Provider: $TTS_PROVIDER"
echo "Output: $OUTPUT_DIR"
echo ""

# Beat narration texts (extracted from beat sheet)
declare -a NARRATIONS=(
    "{{BEAT_1_NARRATION}}"
    "{{BEAT_2_NARRATION}}"
    "{{BEAT_3_NARRATION}}"
)

# Generate audio for each beat
for i in "${!NARRATIONS[@]}"; do
    BEAT_NUM=$(printf "%02d" $((i+1)))
    OUTPUT_FILE="$OUTPUT_DIR/beat-${BEAT_NUM}-narration.mp3"

    echo "🎙️  Generating Beat $BEAT_NUM..."

    if [ "$TTS_PROVIDER" = "elevenlabs" ]; then
        # ElevenLabs API
        curl -X POST "https://api.elevenlabs.io/v1/text-to-speech/{{VOICE_ID}}" \
             -H "xi-api-key: $ELEVENLABS_API_KEY" \
             -H "Content-Type: application/json" \
             -d "{\"text\":\"${NARRATIONS[$i]}\"}" \
             --output "$OUTPUT_FILE"
    elif [ "$TTS_PROVIDER" = "openai" ]; then
        # OpenAI TTS API
        curl https://api.openai.com/v1/audio/speech \
             -H "Authorization: Bearer $OPENAI_API_KEY" \
             -H "Content-Type: application/json" \
             -d "{\"model\":\"tts-1\",\"input\":\"${NARRATIONS[$i]}\",\"voice\":\"alloy\"}" \
             --output "$OUTPUT_FILE"
    else
        # macOS say command
        TEMP_AIFF="$OUTPUT_DIR/beat-${BEAT_NUM}-temp.aiff"
        say -v "{{MACOS_VOICE}}" -o "$TEMP_AIFF" "${NARRATIONS[$i]}"
        ffmpeg -i "$TEMP_AIFF" -acodec libmp3lame -ab 192k "$OUTPUT_FILE" -y
        rm "$TEMP_AIFF"
    fi

    echo "  ✅ Created: $OUTPUT_FILE"
done

echo ""
echo "🎵 Creating master audio file..."

# Create FFmpeg concat list
CONCAT_FILE="$OUTPUT_DIR/concat-list.txt"
> "$CONCAT_FILE"
for i in "${!NARRATIONS[@]}"; do
    BEAT_NUM=$(printf "%02d" $((i+1)))
    echo "file 'beat-${BEAT_NUM}-narration.mp3'" >> "$CONCAT_FILE"
done

# Merge all audio files
ffmpeg -f concat -safe 0 -i "$CONCAT_FILE" -c copy "$OUTPUT_DIR/narration.mp3" -y

echo "✅ Master audio: $OUTPUT_DIR/narration.mp3"
echo ""
echo "🎉 Narration generation complete!"
