#!/bin/bash
# Recording script for: {{TOPIC}}
# Generated by Training Video Generator

set -e

echo "🎬 Training Video Recording Script"
echo "Topic: {{TOPIC}}"
echo "Duration: {{DURATION}} minutes"
echo ""

# Configuration
TOPIC="{{TOPIC}}"
RECORDING_DIR="recordings"
AUTOMATION_SCRIPT="scripts/automation/${TOPIC}-automate.scpt"

# Ensure directories exist
mkdir -p "$RECORDING_DIR"

echo "📋 Pre-recording checklist:"
echo "  ✓ Clean terminal environment"
echo "  ✓ Hide personal information"
echo "  ✓ Close unnecessary applications"
echo "  ✓ Prepare any required files"
echo ""

echo "▶️  To record:"
echo "  1. Press Cmd+Shift+5 to start screen recording"
echo "  2. Select recording area"
echo "  3. Click 'Record'"
echo "  4. Run: osascript $AUTOMATION_SCRIPT"
echo "  5. Wait for automation to complete"
echo "  6. Click stop button in menu bar"
echo "  7. Save as: $RECORDING_DIR/${TOPIC}.mov"
echo ""

read -p "Ready to run automation? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "🚀 Running automation script..."
    osascript "$AUTOMATION_SCRIPT"
    echo "✅ Automation complete!"
else
    echo "❌ Cancelled"
    exit 1
fi
